//! `witchy.lock` — the resolved, pinned dependency graph.
//!
//! Every node carries its exact content hash, its computed runtime *and* build
//! footprints, its determinism class, and provenance. The footprints recorded
//! here are the baseline the capability gate diffs the next resolution against
//! (see [`super::gate`]); the hash makes the build reproducible and
//! tamper-evident.

use std::collections::BTreeSet;
use std::path::Path;

use serde::{Deserialize, Serialize};

use super::footprint::Footprint;
use super::{PmResult, PmError};

pub const LOCKFILE_NAME: &str = "witchy.lock";

#[derive(Debug, Clone, Default, Deserialize, Serialize)]
pub struct Lockfile {
    /// Pinned fingerprint of the coven registry's root signing key (TOFU). A
    /// mismatch on a later build means the registry's key changed — a possible
    /// key compromise — and the build is refused.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry_root: Option<String>,
    /// Pinned TUF snapshot version. If the registry ever presents a *lower*
    /// version, that is a rollback attack and the operation is refused.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry_snapshot_version: Option<u64>,
    /// Sorted by name for a stable, diff-friendly file.
    #[serde(default, rename = "rune")]
    pub runes: Vec<LockedRune>,
}

#[derive(Debug, Clone, Deserialize, Serialize, PartialEq, Eq)]
pub struct LockedRune {
    pub name: String,
    pub version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub registry: Option<String>,
    /// For path/local deps: `path:../util`. Mutually exclusive with `registry`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    pub hash: String,
    #[serde(default)]
    pub runtime_footprint: Vec<String>,
    #[serde(default)]
    pub build_footprint: Vec<String>,
    #[serde(default)]
    pub determinism: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provenance: Option<String>,
}

impl LockedRune {
    pub fn footprint(&self) -> Footprint {
        Footprint {
            runtime: self.runtime_footprint.iter().cloned().collect(),
            build: self.build_footprint.iter().cloned().collect(),
        }
    }

    pub fn set_footprint(&mut self, fp: &Footprint) {
        self.runtime_footprint = fp.runtime.iter().cloned().collect();
        self.build_footprint = fp.build.iter().cloned().collect();
        self.determinism = fp.determinism().to_string();
    }
}

impl Lockfile {
    pub fn load(dir: &Path) -> PmResult<Lockfile> {
        let path = dir.join(LOCKFILE_NAME);
        if !path.exists() {
            return Ok(Lockfile::default());
        }
        let text = std::fs::read_to_string(&path)?;
        toml::from_str(&text).map_err(|e| PmError(format!("invalid {LOCKFILE_NAME}: {e}")))
    }

    pub fn save(&self, dir: &Path) -> PmResult<()> {
        let mut me = self.clone();
        me.runes.sort_by(|a, b| a.name.cmp(&b.name));
        let header = "# witchy.lock — generated by coven. Do not edit by hand.\n\
                      # Pins content hashes + capability footprints for reproducible,\n\
                      # supply-chain-safe builds. Commit this file.\n";
        let body =
            toml::to_string_pretty(&me).map_err(|e| PmError(format!("serialize lockfile: {e}")))?;
        std::fs::write(dir.join(LOCKFILE_NAME), format!("{header}{body}"))?;
        Ok(())
    }

    pub fn find(&self, name: &str) -> Option<&LockedRune> {
        self.runes.iter().find(|r| r.name == name)
    }

    pub fn footprint_of(&self, name: &str) -> Option<Footprint> {
        self.find(name).map(|r| r.footprint())
    }

    /// The aggregate (maximum) authority the whole locked tree could exercise.
    pub fn aggregate_footprint(&self) -> Footprint {
        let mut runtime = BTreeSet::new();
        let mut build = BTreeSet::new();
        for r in &self.runes {
            runtime.extend(r.runtime_footprint.iter().cloned());
            build.extend(r.build_footprint.iter().cloned());
        }
        let mut fp = Footprint { runtime, build };
        fp.normalize();
        fp
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn locked(name: &str, rt: &[&str]) -> LockedRune {
        LockedRune {
            name: name.into(),
            version: "1.0.0".into(),
            registry: Some("coven".into()),
            source: None,
            hash: "sha256:abc".into(),
            runtime_footprint: rt.iter().map(|s| s.to_string()).collect(),
            build_footprint: vec![],
            determinism: "guaranteed".into(),
            provenance: None,
        }
    }

    #[test]
    fn roundtrip_and_lookup() {
        let lf = Lockfile {
            registry_root: None,
            registry_snapshot_version: None,
            runes: vec![locked("acme/json", &[]), locked("acme/http", &["Net"])],
        };
        let tmp = std::env::temp_dir().join(format!("witchy-lock-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&tmp);
        lf.save(&tmp).unwrap();
        let back = Lockfile::load(&tmp).unwrap();
        assert_eq!(back.find("acme/http").unwrap().version, "1.0.0");
        assert!(back.footprint_of("acme/http").unwrap().runtime.contains("Net"));
        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn aggregate_unions_caps() {
        let lf = Lockfile {
            registry_root: None,
            registry_snapshot_version: None,
            runes: vec![locked("a", &["Net"]), locked("b", &["Console"])],
        };
        let agg = lf.aggregate_footprint();
        assert!(agg.runtime.contains("Net"));
        assert!(agg.runtime.contains("Console"));
    }

    #[test]
    fn missing_lock_is_empty() {
        let tmp = std::env::temp_dir().join(format!("witchy-nolock-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&tmp);
        let lf = Lockfile::load(&tmp).unwrap();
        assert!(lf.runes.is_empty());
        let _ = std::fs::remove_dir_all(&tmp);
    }
}
