//! Canonical compiler/private intrinsic catalog.
//!
//! These are not user-facing APIs. They are private entry points generated by
//! the front-end or used by std modules to reach representation-level
//! operations. The catalog is deliberately representation-neutral so syntax,
//! type checking, interpretation, and lowering can share it without reversing
//! the compiler crate dependency graph.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IntrinsicId {
    GeneratedRender,
    GeneratedListPush,
    TryContext,
    Erase,
    Unerase,
    BytesFromString,
    BytesFromList,
    BytesToString,
    BytesLength,
    BytesAt,
    BytesConcat,
    BytesSlice,
    ChannelOpen,
    ChannelSend,
    ChannelRecv,
    ChannelSelect,
    TestingMockDir,
    CompilerDocResultJson,
}

/// A representation-neutral type recipe interpreted by `witchy-types`.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IntrinsicSignature {
    GenericRender,
    GenericListPush,
    TryContext,
    GenericToMessage,
    MessageToGeneric,
    StringToBytes,
    ListIntToBytes,
    BytesToString,
    BytesToInt,
    BytesIntToInt,
    BytesBytesToBytes,
    BytesIntIntToBytes,
    EntriesToReadOnlyDir,
    DeclaredInSource,
    CompilerDocResultJson,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IntrinsicEffect {
    Pure,
    ControlFlow,
    Task,
    Toolchain,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum CapabilityEffect {
    None,
    ConstructsReadOnlyTestDir,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IntrinsicLowering {
    FrontendGenerated,
    Identity,
    Builtin,
    SourceFunction,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum IntrinsicRuntime {
    InterpreterBuiltin,
    SourceFunction,
    Native,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct IntrinsicSpec {
    pub id: IntrinsicId,
    pub name: &'static str,
    pub arity: usize,
    pub signature: IntrinsicSignature,
    pub effect: IntrinsicEffect,
    pub capability_effect: CapabilityEffect,
    pub lowering: IntrinsicLowering,
    pub runtime: IntrinsicRuntime,
    /// Statically named WIR helpers this operation may request.
    pub wir_helpers: &'static [&'static str],
    /// The operation may additionally synthesize a shape-specific helper.
    pub dynamic_wir_helpers: bool,
    pub diagnostic_name: &'static str,
    pub private_callers: &'static [&'static str],
}

const NO_HELPERS: &[&str] = &[];
const NO_PRIVATE_CALLERS: &[&str] = &[];
const MESSAGE_BRIDGE_CALLERS: &[&str] = &["chan", "task"];
const BYTES_BRIDGE_CALLERS: &[&str] = &["bytes"];
const TESTING_BRIDGE_CALLERS: &[&str] = &["testing"];

pub const GENERATED_RENDER: &str = "@render";
pub const GENERATED_LIST_PUSH: &str = "@list_push";
pub const RETIRED_SOURCE_RENDER: &str = "__render";
pub const TRY_CONTEXT: &str = "__try_ctx";

pub const ERASE: &str = "__erase";
pub const UNERASE: &str = "__unerase";

pub const BYTES_FROM_STRING: &str = "__bytes_from_string";
pub const BYTES_FROM_LIST: &str = "__bytes_from_list";
pub const BYTES_TO_STRING: &str = "__bytes_to_string";
pub const BYTES_LENGTH: &str = "__bytes_length";
pub const BYTES_AT: &str = "__bytes_at";
pub const BYTES_CONCAT: &str = "__bytes_concat";
pub const BYTES_SLICE: &str = "__bytes_slice";

pub const CHANNEL_OPEN: &str = "__channel_open";
pub const CHANNEL_SEND: &str = "__channel_send";
pub const CHANNEL_RECV: &str = "__channel_recv";
pub const CHANNEL_SELECT: &str = "__channel_select";

pub const TESTING_MOCK_DIR: &str = "__mock_dir";

pub const COMPILER_DOC_RESULT_JSON: &str = "compiler.__doc_result_json";

pub const ALL: &[IntrinsicSpec] = &[
    IntrinsicSpec {
        id: IntrinsicId::GeneratedRender,
        name: GENERATED_RENDER,
        arity: 1,
        signature: IntrinsicSignature::GenericRender,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["int_to_string", "float_to_str", "concat"],
        dynamic_wir_helpers: true,
        diagnostic_name: "string interpolation",
        private_callers: NO_PRIVATE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::GeneratedListPush,
        name: GENERATED_LIST_PUSH,
        arity: 2,
        signature: IntrinsicSignature::GenericListPush,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["list_push"],
        dynamic_wir_helpers: false,
        diagnostic_name: "list.push",
        private_callers: NO_PRIVATE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::TryContext,
        name: TRY_CONTEXT,
        arity: 2,
        signature: IntrinsicSignature::TryContext,
        effect: IntrinsicEffect::ControlFlow,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::FrontendGenerated,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "? context",
        private_callers: NO_PRIVATE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::Erase,
        name: ERASE,
        arity: 1,
        signature: IntrinsicSignature::GenericToMessage,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Identity,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "message erasure",
        private_callers: MESSAGE_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::Unerase,
        name: UNERASE,
        arity: 1,
        signature: IntrinsicSignature::MessageToGeneric,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Identity,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "message recovery",
        private_callers: MESSAGE_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::BytesFromString,
        name: BYTES_FROM_STRING,
        arity: 1,
        signature: IntrinsicSignature::StringToBytes,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Identity,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "bytes.from_string",
        private_callers: BYTES_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::BytesFromList,
        name: BYTES_FROM_LIST,
        arity: 1,
        signature: IntrinsicSignature::ListIntToBytes,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["bytes_from_list"],
        dynamic_wir_helpers: false,
        diagnostic_name: "bytes.from_list",
        private_callers: BYTES_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::BytesToString,
        name: BYTES_TO_STRING,
        arity: 1,
        signature: IntrinsicSignature::BytesToString,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["bytes_to_string"],
        dynamic_wir_helpers: false,
        diagnostic_name: "bytes.to_string",
        private_callers: BYTES_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::BytesLength,
        name: BYTES_LENGTH,
        arity: 1,
        signature: IntrinsicSignature::BytesToInt,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "bytes.length",
        private_callers: BYTES_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::BytesAt,
        name: BYTES_AT,
        arity: 2,
        signature: IntrinsicSignature::BytesIntToInt,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["bytes_at"],
        dynamic_wir_helpers: false,
        diagnostic_name: "bytes.at",
        private_callers: BYTES_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::BytesConcat,
        name: BYTES_CONCAT,
        arity: 2,
        signature: IntrinsicSignature::BytesBytesToBytes,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["concat"],
        dynamic_wir_helpers: false,
        diagnostic_name: "bytes.concat",
        private_callers: BYTES_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::BytesSlice,
        name: BYTES_SLICE,
        arity: 3,
        signature: IntrinsicSignature::BytesIntIntToBytes,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["bytes_slice"],
        dynamic_wir_helpers: false,
        diagnostic_name: "bytes.slice",
        private_callers: BYTES_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::ChannelOpen,
        name: CHANNEL_OPEN,
        arity: 1,
        signature: IntrinsicSignature::DeclaredInSource,
        effect: IntrinsicEffect::Task,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::SourceFunction,
        runtime: IntrinsicRuntime::SourceFunction,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "channel open",
        private_callers: MESSAGE_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::ChannelSend,
        name: CHANNEL_SEND,
        arity: 2,
        signature: IntrinsicSignature::DeclaredInSource,
        effect: IntrinsicEffect::Task,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::SourceFunction,
        runtime: IntrinsicRuntime::SourceFunction,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "channel send",
        private_callers: MESSAGE_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::ChannelRecv,
        name: CHANNEL_RECV,
        arity: 2,
        signature: IntrinsicSignature::DeclaredInSource,
        effect: IntrinsicEffect::Task,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::SourceFunction,
        runtime: IntrinsicRuntime::SourceFunction,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "channel receive",
        private_callers: MESSAGE_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::ChannelSelect,
        name: CHANNEL_SELECT,
        arity: 2,
        signature: IntrinsicSignature::DeclaredInSource,
        effect: IntrinsicEffect::Task,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::SourceFunction,
        runtime: IntrinsicRuntime::SourceFunction,
        wir_helpers: NO_HELPERS,
        dynamic_wir_helpers: false,
        diagnostic_name: "channel select",
        private_callers: MESSAGE_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::TestingMockDir,
        name: TESTING_MOCK_DIR,
        arity: 1,
        signature: IntrinsicSignature::EntriesToReadOnlyDir,
        effect: IntrinsicEffect::Pure,
        capability_effect: CapabilityEffect::ConstructsReadOnlyTestDir,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::InterpreterBuiltin,
        wir_helpers: &["testing_mock_dir"],
        dynamic_wir_helpers: false,
        diagnostic_name: "testing.mock_dir",
        private_callers: TESTING_BRIDGE_CALLERS,
    },
    IntrinsicSpec {
        id: IntrinsicId::CompilerDocResultJson,
        name: COMPILER_DOC_RESULT_JSON,
        arity: 2,
        signature: IntrinsicSignature::CompilerDocResultJson,
        effect: IntrinsicEffect::Toolchain,
        capability_effect: CapabilityEffect::None,
        lowering: IntrinsicLowering::Builtin,
        runtime: IntrinsicRuntime::Native,
        wir_helpers: &["compiler_doc_result_json"],
        dynamic_wir_helpers: false,
        diagnostic_name: "compiler doc result encoding",
        private_callers: NO_PRIVATE_CALLERS,
    },
];

pub const ERASURE_BRIDGES: &[&str] = &[ERASE, UNERASE];
pub const BYTES_BRIDGES: &[&str] = &[
    BYTES_FROM_STRING,
    BYTES_FROM_LIST,
    BYTES_TO_STRING,
    BYTES_LENGTH,
    BYTES_AT,
    BYTES_CONCAT,
    BYTES_SLICE,
];

pub const CHANNEL_BRIDGES: &[&str] = &[
    CHANNEL_OPEN,
    CHANNEL_SEND,
    CHANNEL_RECV,
    CHANNEL_SELECT,
];

pub fn lookup(name: &str) -> Option<&'static IntrinsicSpec> {
    ALL.iter().find(|spec| spec.name == name)
}

pub fn arity_diagnostic(spec: &IntrinsicSpec, actual: usize) -> String {
    let noun = if spec.arity == 1 { "argument" } else { "arguments" };
    format!(
        "`{}` expects {} {noun}, got {actual}",
        spec.diagnostic_name, spec.arity
    )
}

pub fn is_render(name: &str) -> bool {
    lookup(name).is_some_and(|spec| spec.id == IntrinsicId::GeneratedRender)
}

pub fn is_erasure_bridge(name: &str) -> bool {
    lookup(name).is_some_and(|spec| matches!(spec.id, IntrinsicId::Erase | IntrinsicId::Unerase))
}

pub fn is_bytes_bridge(name: &str) -> bool {
    lookup(name).is_some_and(|spec| {
        matches!(
            spec.id,
            IntrinsicId::BytesFromString
                | IntrinsicId::BytesFromList
                | IntrinsicId::BytesToString
                | IntrinsicId::BytesLength
                | IntrinsicId::BytesAt
                | IntrinsicId::BytesConcat
                | IntrinsicId::BytesSlice
        )
    })
}

pub fn is_channel_bridge(name: &str) -> bool {
    lookup(name).is_some_and(|spec| {
        matches!(
            spec.id,
            IntrinsicId::ChannelOpen
                | IntrinsicId::ChannelSend
                | IntrinsicId::ChannelRecv
                | IntrinsicId::ChannelSelect
        )
    })
}

pub fn private_intrinsic_callers(bare_name: &str) -> Option<&'static [&'static str]> {
    let callers = lookup(bare_name)?.private_callers;
    (!callers.is_empty()).then_some(callers)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeSet;

    #[test]
    fn catalog_names_and_ids_are_unique() {
        let mut names = BTreeSet::new();
        let mut ids = BTreeSet::new();
        for spec in ALL {
            assert!(names.insert(spec.name), "duplicate intrinsic name {}", spec.name);
            assert!(ids.insert(format!("{:?}", spec.id)), "duplicate intrinsic id {:?}", spec.id);
            assert!(!spec.diagnostic_name.is_empty());
        }
    }

    #[test]
    fn bridge_catalog_has_expected_privacy_owners() {
        for name in ERASURE_BRIDGES.iter().chain(CHANNEL_BRIDGES.iter()) {
            assert_eq!(private_intrinsic_callers(name), Some(MESSAGE_BRIDGE_CALLERS));
        }
        for name in BYTES_BRIDGES {
            assert_eq!(private_intrinsic_callers(name), Some(BYTES_BRIDGE_CALLERS));
        }
        assert_eq!(
            private_intrinsic_callers(TESTING_MOCK_DIR),
            Some(TESTING_BRIDGE_CALLERS)
        );
    }

    #[test]
    fn public_constants_resolve_to_catalog_entries() {
        let names = [
            GENERATED_RENDER,
            GENERATED_LIST_PUSH,
            TRY_CONTEXT,
            ERASE,
            UNERASE,
            BYTES_FROM_STRING,
            BYTES_FROM_LIST,
            BYTES_TO_STRING,
            BYTES_LENGTH,
            BYTES_AT,
            BYTES_CONCAT,
            BYTES_SLICE,
            CHANNEL_OPEN,
            CHANNEL_SEND,
            CHANNEL_RECV,
            CHANNEL_SELECT,
            TESTING_MOCK_DIR,
            COMPILER_DOC_RESULT_JSON,
        ];
        for name in names {
            assert_eq!(lookup(name).map(|spec| spec.name), Some(name));
        }
    }

    #[test]
    fn diagnostics_use_catalog_names_and_arities() {
        let at = lookup(BYTES_AT).expect("bytes.at intrinsic");
        assert_eq!(arity_diagnostic(at, 1), "`bytes.at` expects 2 arguments, got 1");

        let from_string = lookup(BYTES_FROM_STRING).expect("bytes.from_string intrinsic");
        assert_eq!(
            arity_diagnostic(from_string, 0),
            "`bytes.from_string` expects 1 argument, got 0"
        );
    }

    #[test]
    fn source_function_arities_match_task_module() {
        let module = crate::parser::parse_module(include_str!("../../../std/task.witchy"))
            .expect("parse std/task");
        for spec in ALL.iter().filter(|spec| spec.runtime == IntrinsicRuntime::SourceFunction) {
            let function = module.items.iter().find_map(|item| match item {
                crate::ast::Item::Function(function) if function.name == spec.name => Some(function),
                _ => None,
            });
            let function = function.unwrap_or_else(|| panic!("{} missing from std/task", spec.name));
            assert_eq!(
                function.params.len(),
                spec.arity,
                "catalog arity drifted from std/task for {}",
                spec.name
            );
        }
    }

    #[test]
    fn native_source_placeholder_matches_catalog_signature() {
        let module = crate::parser::parse_module(include_str!("../../../std/compiler.witchy"))
            .expect("parse std/compiler");
        let bare_name = COMPILER_DOC_RESULT_JSON
            .rsplit_once('.')
            .map_or(COMPILER_DOC_RESULT_JSON, |(_, bare)| bare);
        let function = module.items.iter().find_map(|item| match item {
            crate::ast::Item::Function(function)
                if function.name == bare_name => Some(function),
            _ => None,
        });
        let function = function.expect("compiler doc-result native placeholder");
        let string = crate::ast::Type::Named("String".into(), Vec::new());
        assert_eq!(function.params.len(), lookup(COMPILER_DOC_RESULT_JSON).unwrap().arity);
        assert!(function.params.iter().all(|param| param.ty.as_ref() == Some(&string)));
        assert_eq!(function.ret.as_ref(), Some(&string));
    }

    #[test]
    fn generated_frontend_intrinsics_are_not_std_bridges() {
        assert_eq!(private_intrinsic_callers(GENERATED_RENDER), None);
        assert_eq!(private_intrinsic_callers(GENERATED_LIST_PUSH), None);
        assert_eq!(private_intrinsic_callers(RETIRED_SOURCE_RENDER), None);
        assert_eq!(private_intrinsic_callers(TRY_CONTEXT), None);
        assert_eq!(private_intrinsic_callers(COMPILER_DOC_RESULT_JSON), None);
    }
}
