//! Native backend: transpile a witchy module to Rust source, to be compiled by
//! `rustc`/LLVM into a native binary.
//!
//! witchy's surface (Rust-flavoured words, expression-oriented blocks, `a..b`
//! ranges) maps almost one-to-one onto Rust, so the compute core — functions
//! over `Int`/`Float`/`Bool`/`String`, arithmetic, control flow, recursion,
//! range `for`, `print`/`int_to_string` — transpiles directly and is then
//! optimized by LLVM (which routinely matches or beats Go's compiler). Anything
//! outside that subset returns a clear `Err` rather than emitting wrong code.
//!
//! NOTE: native output is NOT capability-sandboxed (it's an ordinary native
//! binary). It is for trusted, performance-critical code; untrusted code should
//! keep using the wasm `sandbox` path, where only granted host functions exist.

use crate::ast::{BinOp, Block, Expr, Function, Item, Module, Stmt, Type, UnOp};

/// Transpile a whole module's functions to a self-contained Rust program.
pub fn transpile_module(m: &Module) -> Result<String, String> {
    let mut out = String::from("// generated by `witchy native` — do not edit\n");
    out.push_str("#![allow(unused_parens, unused_mut, dead_code)]\n");
    let mut saw_main = false;
    for item in &m.items {
        match item {
            Item::Function(f) => {
                if f.name == "main" {
                    saw_main = true;
                }
                out.push_str(&gen_fn(f)?);
                out.push('\n');
            }
            // Type/trait/alias/impl declarations carry no runtime code the
            // compute subset references; skip them. Actors and consts aren't
            // supported by the native backend yet.
            Item::Type(_) | Item::Trait(_) | Item::TypeAlias { .. } | Item::Impl(_) => {}
            Item::Actor(_) => return Err("native backend: actors are not supported".into()),
            Item::Const { .. } => {
                return Err("native backend: top-level `const` is not supported yet".into())
            }
        }
    }
    if !saw_main {
        return Err("native backend: program has no `main`".into());
    }
    Ok(out)
}

fn gen_fn(f: &Function) -> Result<String, String> {
    if f.is_gen {
        return Err(format!("native backend: generator `{}` is not supported", f.name));
    }
    if !f.bounds.is_empty() {
        return Err(format!(
            "native backend: generic function `{}` (`where` bounds) is not supported",
            f.name
        ));
    }
    let is_main = f.name == "main";
    let mut params = Vec::new();
    for p in &f.params {
        let ty = p
            .ty
            .as_ref()
            .ok_or_else(|| format!("native backend: parameter `{}` needs a type", p.name))?;
        match rust_ty(ty) {
            Some(rt) => params.push(format!("{}: {rt}", p.name)),
            // A capability parameter (e.g. `console: Console`) has no native
            // representation; `main` simply drops it (its `print`s go to stdout).
            None if is_main => {}
            None => {
                return Err(format!(
                    "native backend: unsupported type for parameter `{}`",
                    p.name
                ))
            }
        }
    }
    let name = if is_main { "main".to_string() } else { format!("w_{}", ident(&f.name)) };
    let ret = match &f.ret {
        Some(t) => {
            let rt = rust_ty(t)
                .ok_or_else(|| format!("native backend: unsupported return type of `{}`", f.name))?;
            format!(" -> {rt}")
        }
        None => String::new(),
    };
    let body = gen_block(&f.body, f.ret.is_some())?;
    Ok(format!("fn {name}({}){ret} {body}\n", params.join(", ")))
}

/// Emit a block. In value position (`value`), the final `Expr` statement is the
/// block's value (no trailing `;`); otherwise every statement is terminated.
fn gen_block(b: &Block, value: bool) -> Result<String, String> {
    let mut out = String::from("{\n");
    let n = b.stmts.len();
    for (i, s) in b.stmts.iter().enumerate() {
        let tail = value && i + 1 == n;
        out.push_str("    ");
        out.push_str(&gen_stmt(s, tail)?);
        out.push('\n');
    }
    out.push('}');
    Ok(out)
}

fn gen_stmt(s: &Stmt, tail: bool) -> Result<String, String> {
    Ok(match s {
        Stmt::Let { name, mutable, value } => {
            let m = if *mutable { "mut " } else { "" };
            format!("let {m}{name} = {};", gen_expr(value, true)?)
        }
        Stmt::Assign { name, value } => format!("{name} = {};", gen_expr(value, true)?),
        Stmt::Return(Some(e)) => format!("return {};", gen_expr(e, true)?),
        Stmt::Return(None) => "return;".into(),
        Stmt::Break => "break;".into(),
        Stmt::Continue => "continue;".into(),
        Stmt::Expr(e) if tail => gen_expr(e, true)?,
        Stmt::Expr(e) => format!("{};", gen_expr(e, false)?),
        Stmt::LetTuple { .. } => {
            return Err("native backend: tuple destructuring is not supported yet".into())
        }
        Stmt::Yield(_) => return Err("native backend: `yield` is not supported".into()),
    })
}

fn gen_expr(e: &Expr, value: bool) -> Result<String, String> {
    Ok(match e {
        // Pin integer/float literals so locals infer i64/f64 (Rust would default
        // an integer literal to i32 and break arithmetic with i64 params).
        Expr::Int(n) => format!("{n}i64"),
        Expr::Duration(n) => format!("{n}i64"),
        Expr::Float(x) => format!("{x:?}f64"),
        Expr::Bool(b) => b.to_string(),
        Expr::Str(s) => format!("{s:?}.to_string()"),
        Expr::Var(v) => v.clone(),
        Expr::Unary { op, expr } => {
            let inner = gen_expr(expr, true)?;
            match op {
                UnOp::Neg => format!("(-({inner}))"),
                UnOp::Not => format!("(!({inner}))"),
                UnOp::BitNot => format!("(!({inner}))"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = gen_expr(lhs, true)?;
            let r = gen_expr(rhs, true)?;
            match op {
                BinOp::Concat => format!("format!(\"{{}}{{}}\", {l}, {r})"),
                _ => format!("({l} {} {r})", bin_op(*op)),
            }
        }
        Expr::If { cond, then_block, else_block } => {
            let c = gen_expr(cond, true)?;
            let t = gen_block(then_block, value)?;
            match else_block {
                Some(eb) => format!("if {c} {t} else {}", gen_block(eb, value)?),
                None => format!("if {c} {t}"),
            }
        }
        Expr::While { cond, body } => {
            format!("while {} {}", gen_expr(cond, true)?, gen_block(body, false)?)
        }
        Expr::For { var, iter, body } => match iter.as_ref() {
            Expr::Range { lo, hi, inclusive } => {
                let op = if *inclusive { "..=" } else { ".." };
                format!(
                    "for {var} in {}{op}{} {}",
                    gen_expr(lo, true)?,
                    gen_expr(hi, true)?,
                    gen_block(body, false)?
                )
            }
            _ => {
                return Err(
                    "native backend: `for` over a list is not supported yet (only ranges)".into(),
                )
            }
        },
        Expr::Block(b) => gen_block(b, value)?,
        Expr::Call { name, args } => gen_call(name, args)?,
        other => {
            return Err(format!(
                "native backend: unsupported expression `{}`",
                expr_kind(other)
            ))
        }
    })
}

fn gen_call(name: &str, args: &[Expr]) -> Result<String, String> {
    let arg = |i: usize| gen_expr(&args[i], true);
    Ok(match name {
        // `print(console, x)` — the console capability is dropped; print to stdout.
        "print" if args.len() == 2 => format!("println!(\"{{}}\", {})", arg(1)?),
        "int_to_string" if args.len() == 1 => format!("({}).to_string()", arg(0)?),
        "string_to_int" if args.len() == 1 => {
            format!("({}).parse::<i64>().unwrap()", arg(0)?)
        }
        "print" | "int_to_string" | "string_to_int" => {
            return Err(format!("native backend: wrong arity for `{name}`"))
        }
        // Any other call is a user function (capability/builtin calls outside the
        // subset will surface as an undefined `w_*` at rustc time, which is loud).
        _ => {
            let a: Vec<String> = (0..args.len())
                .map(|i| gen_expr(&args[i], true))
                .collect::<Result<_, _>>()?;
            format!("w_{}({})", ident(name), a.join(", "))
        }
    })
}

/// Make a witchy name a valid Rust identifier: the linker module-qualifies
/// functions as `stem.fn`, and `.` isn't legal in an identifier.
fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

fn rust_ty(t: &Type) -> Option<String> {
    match t {
        Type::Named(n, _) => match n.as_str() {
            "Int" | "Duration" => Some("i64".into()),
            "Float" => Some("f64".into()),
            "Bool" => Some("bool".into()),
            "String" => Some("String".into()),
            _ => None,
        },
        _ => None,
    }
}

fn bin_op(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
        BinOp::Concat => "+",
    }
}

fn expr_kind(e: &Expr) -> &'static str {
    match e {
        Expr::List(_) => "list",
        Expr::Tuple(_) => "tuple",
        Expr::MethodCall { .. } => "method call",
        Expr::Apply { .. } => "function-value application",
        Expr::Ctor { .. } => "constructor",
        Expr::Field { .. } => "field access",
        Expr::Lambda { .. } => "closure",
        Expr::Record { .. } | Expr::RecordUpdate { .. } => "record",
        Expr::Try(_) => "`?`",
        Expr::As { .. } => "`as`",
        Expr::Match { .. } => "match",
        Expr::Range { .. } => "range value",
        Expr::Index { .. } => "index",
        Expr::WhileLet { .. } => "while-let",
        Expr::Spawn { .. } => "spawn",
        _ => "expression",
    }
}
