//! Native backend: transpile a witchy module to Rust source, to be compiled by
//! `rustc`/LLVM into a native binary.
//!
//! witchy's surface (Rust-flavoured words, expression-oriented blocks, `a..b`
//! ranges) maps almost one-to-one onto Rust, so the compute core — functions
//! over `Int`/`Float`/`Bool`/`String`, arithmetic, control flow, recursion,
//! range `for`, `print`/`int_to_string` — transpiles directly and is then
//! optimized by LLVM (which routinely matches or beats Go's compiler). Anything
//! outside that subset returns a clear `Err` rather than emitting wrong code.
//!
//! NOTE: native output is NOT capability-sandboxed (it's an ordinary native
//! binary). It is for trusted, performance-critical code; untrusted code should
//! keep using the wasm `sandbox` path, where only granted host functions exist.

use crate::ast::{BinOp, Block, Expr, Function, Item, Module, Stmt, Type, UnOp};
use std::cell::RefCell;
use std::collections::HashMap;

thread_local! {
    /// Field names of each supported record type (single-variant, named fields,
    /// all-supported field types), keyed by constructor name. Populated up front
    /// by `transpile_module` so a positional `Ctor` can be emitted as a named
    /// Rust struct literal, and so record-typed params resolve in `rust_ty`.
    static RECORD_FIELDS: RefCell<HashMap<String, Vec<String>>> = RefCell::new(HashMap::new());
}

/// Transpile a whole module's record types and functions to a self-contained
/// Rust program.
pub fn transpile_module(m: &Module) -> Result<String, String> {
    RECORD_FIELDS.with(|r| r.borrow_mut().clear());
    let mut out = String::from("// generated by `witchy native` — do not edit\n");
    out.push_str("#![allow(unused_parens, unused_mut, dead_code)]\n");
    // First pass: emit a Rust struct for each supported record type and register
    // its field names, so later constructors/params resolve.
    for item in &m.items {
        if let Item::Type(td) = item {
            if let Some(s) = gen_record(td) {
                out.push_str(&s);
            }
        }
    }
    let mut saw_main = false;
    for item in &m.items {
        match item {
            Item::Function(f) => {
                if f.name == "main" {
                    saw_main = true;
                }
                out.push_str(&gen_fn(f)?);
                out.push('\n');
            }
            // Records are handled above; other type/trait/alias/impl decls carry
            // no runtime code the subset references. Actors/consts aren't yet
            // supported by the native backend.
            Item::Type(_) | Item::Trait(_) | Item::TypeAlias { .. } | Item::Impl(_) => {}
            Item::Actor(_) => return Err("native backend: actors are not supported".into()),
            Item::Const { .. } => {
                return Err("native backend: top-level `const` is not supported yet".into())
            }
        }
    }
    if !saw_main {
        return Err("native backend: program has no `main`".into());
    }
    Ok(out)
}

/// Emit a Rust struct for a single-variant, named-field record whose fields are
/// all supported, and register its fields. Returns `None` (skips) otherwise — a
/// multi-variant enum, a positional variant, or an unsupported field type — so a
/// later use of it surfaces a clear error instead.
fn gen_record(td: &crate::ast::TypeDef) -> Option<String> {
    let [v] = td.variants.as_slice() else { return None };
    if v.field_names.len() != v.fields.len() || v.field_names.is_empty() {
        return None;
    }
    let mut fields = Vec::new();
    let mut all_copy = true;
    for (name, ty) in v.field_names.iter().zip(&v.fields) {
        let rt = rust_ty(ty)?;
        all_copy &= matches!(ty, Type::Named(n, _) if n == "Int" || n == "Float" || n == "Bool" || n == "Duration");
        fields.push(format!("    {name}: {rt},"));
    }
    RECORD_FIELDS.with(|r| {
        r.borrow_mut().insert(v.name.clone(), v.field_names.clone());
    });
    let derive = if all_copy {
        "#[derive(Clone, Copy)]"
    } else {
        "#[derive(Clone)]"
    };
    Some(format!(
        "{derive}\nstruct {} {{\n{}\n}}\n",
        v.name,
        fields.join("\n")
    ))
}

fn gen_fn(f: &Function) -> Result<String, String> {
    if f.is_gen {
        return Err(format!("native backend: generator `{}` is not supported", f.name));
    }
    if !f.bounds.is_empty() {
        return Err(format!(
            "native backend: generic function `{}` (`where` bounds) is not supported",
            f.name
        ));
    }
    let is_main = f.name == "main";
    let mut params = Vec::new();
    for p in &f.params {
        let ty = p
            .ty
            .as_ref()
            .ok_or_else(|| format!("native backend: parameter `{}` needs a type", p.name))?;
        match rust_ty(ty) {
            Some(rt) => params.push(format!("{}: {rt}", p.name)),
            // A capability parameter (e.g. `console: Console`) has no native
            // representation; `main` simply drops it (its `print`s go to stdout).
            None if is_main => {}
            None => {
                return Err(format!(
                    "native backend: unsupported type for parameter `{}`",
                    p.name
                ))
            }
        }
    }
    let name = if is_main { "main".to_string() } else { format!("w_{}", ident(&f.name)) };
    let ret = match &f.ret {
        Some(t) => {
            let rt = rust_ty(t)
                .ok_or_else(|| format!("native backend: unsupported return type of `{}`", f.name))?;
            format!(" -> {rt}")
        }
        None => String::new(),
    };
    let body = gen_block(&f.body, f.ret.is_some())?;
    Ok(format!("fn {name}({}){ret} {body}\n", params.join(", ")))
}

/// Emit a block. In value position (`value`), the final `Expr` statement is the
/// block's value (no trailing `;`); otherwise every statement is terminated.
fn gen_block(b: &Block, value: bool) -> Result<String, String> {
    let mut out = String::from("{\n");
    let n = b.stmts.len();
    for (i, s) in b.stmts.iter().enumerate() {
        let tail = value && i + 1 == n;
        out.push_str("    ");
        out.push_str(&gen_stmt(s, tail)?);
        out.push('\n');
    }
    out.push('}');
    Ok(out)
}

fn gen_stmt(s: &Stmt, tail: bool) -> Result<String, String> {
    Ok(match s {
        Stmt::Let { name, mutable, value } => {
            let m = if *mutable { "mut " } else { "" };
            format!("let {m}{name} = {};", gen_expr(value, true)?)
        }
        Stmt::Assign { name, value } => format!("{name} = {};", gen_expr(value, true)?),
        Stmt::Return(Some(e)) => format!("return {};", gen_expr(e, true)?),
        Stmt::Return(None) => "return;".into(),
        Stmt::Break => "break;".into(),
        Stmt::Continue => "continue;".into(),
        Stmt::Expr(e) if tail => gen_expr(e, true)?,
        Stmt::Expr(e) => format!("{};", gen_expr(e, false)?),
        Stmt::LetTuple { names, value } => {
            format!("let ({}) = {};", names.join(", "), gen_expr(value, true)?)
        }
        Stmt::Yield(_) => return Err("native backend: `yield` is not supported".into()),
    })
}

fn gen_expr(e: &Expr, value: bool) -> Result<String, String> {
    Ok(match e {
        // Pin integer/float literals so locals infer i64/f64 (Rust would default
        // an integer literal to i32 and break arithmetic with i64 params).
        Expr::Int(n) => format!("{n}i64"),
        Expr::Duration(n) => format!("{n}i64"),
        Expr::Float(x) => format!("{x:?}f64"),
        Expr::Bool(b) => b.to_string(),
        Expr::Str(s) => format!("{s:?}.to_string()"),
        Expr::Var(v) => v.clone(),
        Expr::Unary { op, expr } => {
            let inner = gen_expr(expr, true)?;
            match op {
                UnOp::Neg => format!("(-({inner}))"),
                UnOp::Not => format!("(!({inner}))"),
                UnOp::BitNot => format!("(!({inner}))"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = gen_expr(lhs, true)?;
            let r = gen_expr(rhs, true)?;
            match op {
                BinOp::Concat => format!("format!(\"{{}}{{}}\", {l}, {r})"),
                _ => format!("({l} {} {r})", bin_op(*op)),
            }
        }
        Expr::If { cond, then_block, else_block } => {
            let c = gen_expr(cond, true)?;
            let t = gen_block(then_block, value)?;
            match else_block {
                Some(eb) => format!("if {c} {t} else {}", gen_block(eb, value)?),
                None => format!("if {c} {t}"),
            }
        }
        Expr::While { cond, body } => {
            format!("while {} {}", gen_expr(cond, true)?, gen_block(body, false)?)
        }
        Expr::For { var, iter, body } => match iter.as_ref() {
            Expr::Range { lo, hi, inclusive } => {
                let op = if *inclusive { "..=" } else { ".." };
                format!(
                    "for {var} in {}{op}{} {}",
                    gen_expr(lo, true)?,
                    gen_expr(hi, true)?,
                    gen_block(body, false)?
                )
            }
            _ => {
                return Err(
                    "native backend: `for` over a list is not supported yet (only ranges)".into(),
                )
            }
        },
        Expr::Block(b) => gen_block(b, value)?,
        Expr::Call { name, args } => gen_call(name, args)?,
        // `match` maps to a Rust match; non-exhaustive matches (no catch-all) are
        // rejected by rustc, which is safe (the program just stays wasm-only).
        Expr::Match { scrutinee, arms } => {
            let mut out = format!("match {} {{\n", gen_expr(scrutinee, true)?);
            for arm in arms {
                let guard = match &arm.guard {
                    Some(g) => format!(" if {}", gen_expr(g, true)?),
                    None => String::new(),
                };
                out.push_str(&format!(
                    "    {}{guard} => {},\n",
                    gen_pattern(&arm.pattern)?,
                    gen_expr(&arm.body, value)?
                ));
            }
            out.push('}');
            out
        }
        // Record construction (a positional `Ctor` after `records::lower`) ->
        // a named Rust struct literal, using the registered field order.
        Expr::Ctor { name, args } => {
            let fields = RECORD_FIELDS.with(|r| r.borrow().get(name).cloned());
            match fields {
                Some(fnames) if fnames.len() == args.len() => {
                    let parts: Result<Vec<String>, String> = fnames
                        .iter()
                        .zip(args)
                        .map(|(fname, a)| Ok(format!("{fname}: {}", gen_expr(a, true)?)))
                        .collect();
                    format!("{name} {{ {} }}", parts?.join(", "))
                }
                _ => {
                    return Err(format!(
                        "native backend: `{name}` is not a supported record constructor (enum variants aren't supported yet)"
                    ))
                }
            }
        }
        // Field read yields a value copy (clone), preserving value semantics.
        Expr::Field { base, field } => format!("({}).{field}.clone()", gen_expr(base, true)?),
        // A tuple literal: `(a, b)`. A 1-tuple needs the trailing comma.
        Expr::Tuple(items) => {
            let parts: Vec<String> = items
                .iter()
                .map(|x| gen_expr(x, true))
                .collect::<Result<_, _>>()?;
            if parts.len() == 1 {
                format!("({},)", parts[0])
            } else {
                format!("({})", parts.join(", "))
            }
        }
        other => {
            return Err(format!(
                "native backend: unsupported expression `{}`",
                expr_kind(other)
            ))
        }
    })
}

fn gen_call(name: &str, args: &[Expr]) -> Result<String, String> {
    let arg = |i: usize| gen_expr(&args[i], true);
    Ok(match name {
        // `print(console, x)` — the console capability is dropped; print to stdout.
        "print" if args.len() == 2 => format!("println!(\"{{}}\", {})", arg(1)?),
        "int_to_string" if args.len() == 1 => format!("({}).to_string()", arg(0)?),
        "string_to_int" if args.len() == 1 => {
            format!("({}).parse::<i64>().unwrap()", arg(0)?)
        }
        "print" | "int_to_string" | "string_to_int" => {
            return Err(format!("native backend: wrong arity for `{name}`"))
        }
        // Any other call is a user function (capability/builtin calls outside the
        // subset will surface as an undefined `w_*` at rustc time, which is loud).
        _ => {
            let a: Vec<String> = (0..args.len())
                .map(|i| gen_expr(&args[i], true))
                .collect::<Result<_, _>>()?;
            format!("w_{}({})", ident(name), a.join(", "))
        }
    })
}

fn gen_pattern(p: &crate::ast::Pattern) -> Result<String, String> {
    use crate::ast::Pattern;
    Ok(match p {
        Pattern::Wildcard => "_".into(),
        Pattern::Var(n) => n.clone(),
        Pattern::Int(n) => format!("{n}"),
        Pattern::Bool(b) => b.to_string(),
        Pattern::Tuple(ps) => {
            let parts: Vec<String> = ps.iter().map(gen_pattern).collect::<Result<_, _>>()?;
            format!("({})", parts.join(", "))
        }
        Pattern::Str(_) => {
            return Err("native backend: string patterns in `match` are not supported yet".into())
        }
        Pattern::Ctor { .. } => {
            return Err(
                "native backend: constructor patterns (enums/records) are not supported yet".into(),
            )
        }
        Pattern::List { .. } => {
            return Err("native backend: list patterns in `match` are not supported yet".into())
        }
    })
}

/// Make a witchy name a valid Rust identifier: the linker module-qualifies
/// functions as `stem.fn`, and `.` isn't legal in an identifier.
fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

fn rust_ty(t: &Type) -> Option<String> {
    match t {
        Type::Named(n, _) => match n.as_str() {
            "Int" | "Duration" => Some("i64".into()),
            "Float" => Some("f64".into()),
            "Bool" => Some("bool".into()),
            "String" => Some("String".into()),
            // A user record type maps to its Rust struct (if registered).
            other if RECORD_FIELDS.with(|r| r.borrow().contains_key(other)) => {
                Some(other.to_string())
            }
            _ => None,
        },
        // A tuple maps to a Rust tuple, supported when all elements are.
        Type::Tuple(ts) => {
            let parts: Option<Vec<String>> = ts.iter().map(rust_ty).collect();
            parts.map(|p| format!("({})", p.join(", ")))
        }
        _ => None,
    }
}

fn bin_op(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
        BinOp::Concat => "+",
    }
}

fn expr_kind(e: &Expr) -> &'static str {
    match e {
        Expr::List(_) => "list",
        Expr::Tuple(_) => "tuple",
        Expr::MethodCall { .. } => "method call",
        Expr::Apply { .. } => "function-value application",
        Expr::Ctor { .. } => "constructor",
        Expr::Field { .. } => "field access",
        Expr::Lambda { .. } => "closure",
        Expr::Record { .. } | Expr::RecordUpdate { .. } => "record",
        Expr::Try(_) => "`?`",
        Expr::As { .. } => "`as`",
        Expr::Match { .. } => "match",
        Expr::Range { .. } => "range value",
        Expr::Index { .. } => "index",
        Expr::WhileLet { .. } => "while-let",
        Expr::Spawn { .. } => "spawn",
        _ => "expression",
    }
}
