//! Native backend: transpile a witchy module to Rust source, to be compiled by
//! `rustc`/LLVM into a native binary.
//!
//! witchy's surface (Rust-flavoured words, expression-oriented blocks, `a..b`
//! ranges) maps almost one-to-one onto Rust, so the compute core — functions
//! over `Int`/`Float`/`Bool`/`String`, arithmetic, control flow, recursion,
//! range `for`, `print`/`int_to_string` — transpiles directly and is then
//! optimized by LLVM (which routinely matches or beats Go's compiler). Anything
//! outside that subset returns a clear `Err` rather than emitting wrong code.
//!
//! NOTE: native output is NOT capability-sandboxed (it's an ordinary native
//! binary). It is for trusted, performance-critical code; untrusted code should
//! keep using the wasm `sandbox` path, where only granted host functions exist.

use crate::ast::{BinOp, Block, Expr, Function, Item, Module, Stmt, Type, UnOp};
use std::cell::RefCell;
use std::collections::{HashMap, HashSet};

thread_local! {
    /// Field names of each supported record type (single-variant, named fields,
    /// all-supported field types), keyed by constructor name. Populated up front
    /// by `transpile_module` so a positional `Ctor` can be emitted as a named
    /// Rust struct literal, and so record-typed params resolve in `rust_ty`.
    static RECORD_FIELDS: RefCell<HashMap<String, Vec<String>>> = RefCell::new(HashMap::new());
    /// Each supported enum's variant name -> enum name, so a constructor or a
    /// constructor pattern can be qualified as `Enum::Variant`.
    static VARIANT_TO_ENUM: RefCell<HashMap<String, String>> = RefCell::new(HashMap::new());
    /// The names of supported enum types (for `rust_ty`).
    static ENUM_NAMES: RefCell<HashSet<String>> = RefCell::new(HashSet::new());
    /// Per (emitted) function, whether each parameter is a by-value collection
    /// (`List`/`String`) — those owned params are cloned at call sites so the
    /// caller keeps its value (witchy value semantics; Rust would otherwise move
    /// it and reject the caller's later use).
    static FN_PARAM_CLONE: RefCell<HashMap<String, Vec<bool>>> = RefCell::new(HashMap::new());
}

fn fn_rust_name(f: &Function) -> String {
    if f.name == "main" {
        "main".to_string()
    } else {
        format!("w_{}", ident(&f.name))
    }
}

fn is_collection(t: &Option<Type>) -> bool {
    matches!(t, Some(Type::Named(n, _)) if n == "List" || n == "String")
}

/// Transpile a whole module's record/enum types and functions to a
/// self-contained Rust program.
pub fn transpile_module(m: &Module) -> Result<String, String> {
    RECORD_FIELDS.with(|r| r.borrow_mut().clear());
    VARIANT_TO_ENUM.with(|r| r.borrow_mut().clear());
    ENUM_NAMES.with(|r| r.borrow_mut().clear());
    FN_PARAM_CLONE.with(|m| m.borrow_mut().clear());
    // Record which params are by-value collections, so calls clone them.
    for item in &m.items {
        if let Item::Function(f) = item {
            let clones = f.params.iter().map(|p| is_collection(&p.ty)).collect();
            FN_PARAM_CLONE.with(|map| map.borrow_mut().insert(fn_rust_name(f), clones));
        }
    }
    let mut out = String::from("// generated by `witchy native` — do not edit\n");
    out.push_str("#![allow(unused_parens, unused_mut, dead_code, nonstandard_style)]\n");
    // First pass: emit a Rust struct/enum for each supported user type and
    // register it, so later constructors/patterns/params resolve.
    for item in &m.items {
        if let Item::Type(td) = item {
            if let Some(s) = gen_record(td) {
                out.push_str(&s);
            } else if let Some(s) = gen_enum(td) {
                out.push_str(&s);
            }
        }
    }
    let mut saw_main = false;
    for item in &m.items {
        match item {
            Item::Function(f) => {
                if f.name == "main" {
                    saw_main = true;
                }
                out.push_str(&gen_fn(f)?);
                out.push('\n');
            }
            // Records are handled above; other type/trait/alias/impl decls carry
            // no runtime code the subset references. Actors/consts aren't yet
            // supported by the native backend.
            Item::Type(_) | Item::Trait(_) | Item::TypeAlias { .. } | Item::Impl(_) => {}
            Item::Actor(_) => return Err("native backend: actors are not supported".into()),
            Item::Const { .. } => {
                return Err("native backend: top-level `const` is not supported yet".into())
            }
        }
    }
    if !saw_main {
        return Err("native backend: program has no `main`".into());
    }
    Ok(out)
}

/// Emit a Rust struct for a single-variant, named-field record whose fields are
/// all supported, and register its fields. Returns `None` (skips) otherwise — a
/// multi-variant enum, a positional variant, or an unsupported field type — so a
/// later use of it surfaces a clear error instead.
fn gen_record(td: &crate::ast::TypeDef) -> Option<String> {
    let [v] = td.variants.as_slice() else { return None };
    if v.field_names.len() != v.fields.len() || v.field_names.is_empty() {
        return None;
    }
    let mut fields = Vec::new();
    let mut all_copy = true;
    for (name, ty) in v.field_names.iter().zip(&v.fields) {
        let rt = rust_ty(ty)?;
        all_copy &= matches!(ty, Type::Named(n, _) if n == "Int" || n == "Float" || n == "Bool" || n == "Duration");
        fields.push(format!("    {name}: {rt},"));
    }
    RECORD_FIELDS.with(|r| {
        r.borrow_mut().insert(v.name.clone(), v.field_names.clone());
    });
    let derive = if all_copy {
        "#[derive(Clone, Copy)]"
    } else {
        "#[derive(Clone)]"
    };
    Some(format!(
        "{derive}\nstruct {} {{\n{}\n}}\n",
        v.name,
        fields.join("\n")
    ))
}

/// Emit a Rust enum for a multi-variant type with positional variants whose
/// fields are all supported concrete types (so generic types like Option/Result,
/// whose fields are type variables, are skipped — `rust_ty` returns `None`).
/// Returns `None` (skips) for single-variant types, struct-style variants, or an
/// unsupported field type, so a later use surfaces a clear error.
fn gen_enum(td: &crate::ast::TypeDef) -> Option<String> {
    if td.variants.len() < 2 {
        return None;
    }
    let mut variants = Vec::new();
    let mut all_copy = true;
    for v in &td.variants {
        if !v.field_names.is_empty() {
            return None; // struct-style enum variant: not supported yet
        }
        let mut tys = Vec::new();
        for ty in &v.fields {
            tys.push(rust_ty(ty)?);
            all_copy &= matches!(ty, Type::Named(n, _) if n == "Int" || n == "Float" || n == "Bool" || n == "Duration");
        }
        if tys.is_empty() {
            variants.push(format!("    {}", v.name));
        } else {
            variants.push(format!("    {}({})", v.name, tys.join(", ")));
        }
    }
    for v in &td.variants {
        VARIANT_TO_ENUM.with(|m| m.borrow_mut().insert(v.name.clone(), td.name.clone()));
    }
    ENUM_NAMES.with(|s| s.borrow_mut().insert(td.name.clone()));
    let derive = if all_copy {
        "#[derive(Clone, Copy)]"
    } else {
        "#[derive(Clone)]"
    };
    Some(format!(
        "{derive}\nenum {} {{\n{}\n}}\n",
        td.name,
        variants.join(",\n")
    ))
}

fn gen_fn(f: &Function) -> Result<String, String> {
    if f.is_gen {
        return Err(format!("native backend: generator `{}` is not supported", f.name));
    }
    if !f.bounds.is_empty() {
        return Err(format!(
            "native backend: generic function `{}` (`where` bounds) is not supported",
            f.name
        ));
    }
    let is_main = f.name == "main";
    let mut params = Vec::new();
    for p in &f.params {
        let ty = p
            .ty
            .as_ref()
            .ok_or_else(|| format!("native backend: parameter `{}` needs a type", p.name))?;
        match rust_ty(ty) {
            Some(rt) => params.push(format!("{}: {rt}", p.name)),
            // A capability parameter (e.g. `console: Console`) has no native
            // representation; `main` simply drops it (its `print`s go to stdout).
            None if is_main => {}
            None => {
                return Err(format!(
                    "native backend: unsupported type for parameter `{}`",
                    p.name
                ))
            }
        }
    }
    let name = fn_rust_name(f);
    let ret = match &f.ret {
        Some(t) => {
            let rt = rust_ty(t)
                .ok_or_else(|| format!("native backend: unsupported return type of `{}`", f.name))?;
            format!(" -> {rt}")
        }
        None => String::new(),
    };
    let body = gen_block(&f.body, f.ret.is_some())?;
    Ok(format!("fn {name}({}){ret} {body}\n", params.join(", ")))
}

/// Emit a block. In value position (`value`), the final `Expr` statement is the
/// block's value (no trailing `;`); otherwise every statement is terminated.
fn gen_block(b: &Block, value: bool) -> Result<String, String> {
    let mut out = String::from("{\n");
    let n = b.stmts.len();
    for (i, s) in b.stmts.iter().enumerate() {
        let tail = value && i + 1 == n;
        out.push_str("    ");
        out.push_str(&gen_stmt(s, tail)?);
        out.push('\n');
    }
    out.push('}');
    Ok(out)
}

fn gen_stmt(s: &Stmt, tail: bool) -> Result<String, String> {
    Ok(match s {
        Stmt::Let { name, mutable, value } => {
            let m = if *mutable { "mut " } else { "" };
            format!("let {m}{name} = {};", gen_expr(value, true)?)
        }
        Stmt::Assign { name, value } => format!("{name} = {};", gen_expr(value, true)?),
        Stmt::Return(Some(e)) => format!("return {};", gen_expr(e, true)?),
        Stmt::Return(None) => "return;".into(),
        Stmt::Break => "break;".into(),
        Stmt::Continue => "continue;".into(),
        Stmt::Expr(e) if tail => gen_expr(e, true)?,
        Stmt::Expr(e) => format!("{};", gen_expr(e, false)?),
        Stmt::LetTuple { names, value } => {
            format!("let ({}) = {};", names.join(", "), gen_expr(value, true)?)
        }
        Stmt::Yield(_) => return Err("native backend: `yield` is not supported".into()),
    })
}

fn gen_expr(e: &Expr, value: bool) -> Result<String, String> {
    Ok(match e {
        // Pin integer/float literals so locals infer i64/f64 (Rust would default
        // an integer literal to i32 and break arithmetic with i64 params).
        Expr::Int(n) => format!("{n}i64"),
        Expr::Duration(n) => format!("{n}i64"),
        Expr::Float(x) => format!("{x:?}f64"),
        Expr::Bool(b) => b.to_string(),
        Expr::Str(s) => format!("{s:?}.to_string()"),
        Expr::Var(v) => v.clone(),
        Expr::Unary { op, expr } => {
            let inner = gen_expr(expr, true)?;
            match op {
                UnOp::Neg => format!("(-({inner}))"),
                UnOp::Not => format!("(!({inner}))"),
                UnOp::BitNot => format!("(!({inner}))"),
            }
        }
        Expr::Binary { op, lhs, rhs } => {
            let l = gen_expr(lhs, true)?;
            let r = gen_expr(rhs, true)?;
            match op {
                BinOp::Concat => format!("format!(\"{{}}{{}}\", {l}, {r})"),
                _ => format!("({l} {} {r})", bin_op(*op)),
            }
        }
        Expr::If { cond, then_block, else_block } => {
            let c = gen_expr(cond, true)?;
            let t = gen_block(then_block, value)?;
            match else_block {
                Some(eb) => format!("if {c} {t} else {}", gen_block(eb, value)?),
                None => format!("if {c} {t}"),
            }
        }
        Expr::While { cond, body } => {
            format!("while {} {}", gen_expr(cond, true)?, gen_block(body, false)?)
        }
        Expr::For { var, iter, body } => match iter.as_ref() {
            Expr::Range { lo, hi, inclusive } => {
                let op = if *inclusive { "..=" } else { ".." };
                format!(
                    "for {var} in {}{op}{} {}",
                    gen_expr(lo, true)?,
                    gen_expr(hi, true)?,
                    gen_block(body, false)?
                )
            }
            // Iterate a list by shared borrow (so the list survives the loop) and
            // bind each element as a value copy, matching value semantics.
            _ => format!(
                "for {var}__item in &({}) {{ let {var} = ({var}__item).clone(); {} }}",
                gen_expr(iter, true)?,
                gen_block(body, false)?
            ),
        },
        Expr::Block(b) => gen_block(b, value)?,
        Expr::Call { name, args } => gen_call(name, args)?,
        // `match` maps to a Rust match; non-exhaustive matches (no catch-all) are
        // rejected by rustc, which is safe (the program just stays wasm-only).
        Expr::Match { scrutinee, arms } => {
            let mut out = format!("match {} {{\n", gen_expr(scrutinee, true)?);
            for arm in arms {
                let guard = match &arm.guard {
                    Some(g) => format!(" if {}", gen_expr(g, true)?),
                    None => String::new(),
                };
                out.push_str(&format!(
                    "    {}{guard} => {},\n",
                    gen_pattern(&arm.pattern)?,
                    gen_expr(&arm.body, value)?
                ));
            }
            out.push('}');
            out
        }
        // Record construction (a positional `Ctor` after `records::lower`) ->
        // a named Rust struct literal, using the registered field order.
        // Built-in Option/Result constructors map straight to Rust's.
        Expr::Ctor { name, args } if matches!((name.as_str(), args.len()), ("None", 0) | ("Some", 1) | ("Ok", 1) | ("Err", 1)) => {
            if name == "None" {
                "None".to_string()
            } else {
                format!("{name}({})", gen_expr(&args[0], true)?)
            }
        }
        Expr::Ctor { name, args } => {
            if let Some(fnames) = RECORD_FIELDS.with(|r| r.borrow().get(name).cloned()) {
                if fnames.len() != args.len() {
                    return Err(format!("native backend: wrong field count for record `{name}`"));
                }
                let parts: Result<Vec<String>, String> = fnames
                    .iter()
                    .zip(args)
                    .map(|(fname, a)| Ok(format!("{fname}: {}", gen_expr(a, true)?)))
                    .collect();
                format!("{name} {{ {} }}", parts?.join(", "))
            } else if let Some(en) = VARIANT_TO_ENUM.with(|m| m.borrow().get(name).cloned()) {
                if args.is_empty() {
                    format!("{en}::{name}")
                } else {
                    let parts: Result<Vec<String>, String> =
                        args.iter().map(|a| gen_expr(a, true)).collect();
                    format!("{en}::{name}({})", parts?.join(", "))
                }
            } else {
                return Err(format!(
                    "native backend: `{name}` is not a supported record/enum constructor (generic types like Option/Result aren't supported yet)"
                ));
            }
        }
        // Field read yields a value copy (clone), preserving value semantics.
        Expr::Field { base, field } => format!("({}).{field}.clone()", gen_expr(base, true)?),
        // `e?` propagates an Option/Result exactly as Rust's `?`.
        Expr::Try(inner) => format!("({})?", gen_expr(inner, true)?),
        // A list literal -> a Rust `vec![..]` (element type inferred by rustc).
        Expr::List(items) => {
            let parts: Vec<String> = items
                .iter()
                .map(|x| gen_expr(x, true))
                .collect::<Result<_, _>>()?;
            format!("vec![{}]", parts.join(", "))
        }
        // A tuple literal: `(a, b)`. A 1-tuple needs the trailing comma.
        Expr::Tuple(items) => {
            let parts: Vec<String> = items
                .iter()
                .map(|x| gen_expr(x, true))
                .collect::<Result<_, _>>()?;
            if parts.len() == 1 {
                format!("({},)", parts[0])
            } else {
                format!("({})", parts.join(", "))
            }
        }
        other => {
            return Err(format!(
                "native backend: unsupported expression `{}`",
                expr_kind(other)
            ))
        }
    })
}

fn gen_call(name: &str, args: &[Expr]) -> Result<String, String> {
    let arg = |i: usize| gen_expr(&args[i], true);
    Ok(match name {
        // `print(console, x)` — the console capability is dropped; print to stdout.
        "print" if args.len() == 2 => format!("println!(\"{{}}\", {})", arg(1)?),
        "int_to_string" if args.len() == 1 => format!("({}).to_string()", arg(0)?),
        "string_to_int" if args.len() == 1 => {
            format!("({}).parse::<i64>().unwrap()", arg(0)?)
        }
        // List builtins. `push`/`concat` consume the list and return it (so the
        // common `acc = push(acc, x)` is an O(1) in-place append, and Rust's
        // move-checking enforces value semantics on any reuse).
        "length" if args.len() == 1 => format!("(({}).len() as i64)", arg(0)?),
        "at" if args.len() == 2 => format!("({})[({}) as usize].clone()", arg(0)?, arg(1)?),
        "push" if args.len() == 2 => {
            format!("{{ let mut __v = {}; __v.push({}); __v }}", arg(0)?, arg(1)?)
        }
        "concat" if args.len() == 2 => {
            format!("{{ let mut __v = {}; __v.extend({}); __v }}", arg(0)?, arg(1)?)
        }
        "print" | "int_to_string" | "string_to_int" => {
            return Err(format!("native backend: wrong arity for `{name}`"))
        }
        // Any other call is a user function (capability/builtin calls outside the
        // subset will surface as an undefined `w_*` at rustc time, which is loud).
        _ => {
            let fname = format!("w_{}", ident(name));
            let clones = FN_PARAM_CLONE.with(|m| m.borrow().get(&fname).cloned());
            let a: Vec<String> = args
                .iter()
                .enumerate()
                .map(|(i, x)| {
                    let s = gen_expr(x, true)?;
                    // A by-value collection param is cloned so the caller keeps it.
                    let clone = clones.as_ref().is_some_and(|c| c.get(i) == Some(&true));
                    Ok(if clone { format!("({s}).clone()") } else { s })
                })
                .collect::<Result<Vec<String>, String>>()?;
            format!("{fname}({})", a.join(", "))
        }
    })
}

fn gen_pattern(p: &crate::ast::Pattern) -> Result<String, String> {
    use crate::ast::Pattern;
    Ok(match p {
        Pattern::Wildcard => "_".into(),
        Pattern::Var(n) => n.clone(),
        Pattern::Int(n) => format!("{n}"),
        Pattern::Bool(b) => b.to_string(),
        Pattern::Tuple(ps) => {
            let parts: Vec<String> = ps.iter().map(gen_pattern).collect::<Result<_, _>>()?;
            format!("({})", parts.join(", "))
        }
        Pattern::Str(_) => {
            return Err("native backend: string patterns in `match` are not supported yet".into())
        }
        // Built-in Option/Result patterns map straight to Rust's.
        Pattern::Ctor { name, args }
            if matches!((name.as_str(), args.len()), ("None", 0) | ("Some", 1) | ("Ok", 1) | ("Err", 1)) =>
        {
            if name == "None" {
                "None".to_string()
            } else {
                format!("{name}({})", gen_pattern(&args[0])?)
            }
        }
        Pattern::Ctor { name, args } => {
            let en = VARIANT_TO_ENUM
                .with(|m| m.borrow().get(name).cloned())
                .ok_or_else(|| {
                    format!(
                        "native backend: constructor pattern `{name}` (a generic user type's variants aren't supported yet)"
                    )
                })?;
            if args.is_empty() {
                format!("{en}::{name}")
            } else {
                let parts: Vec<String> = args.iter().map(gen_pattern).collect::<Result<_, _>>()?;
                format!("{en}::{name}({})", parts.join(", "))
            }
        }
        Pattern::List { .. } => {
            return Err("native backend: list patterns in `match` are not supported yet".into())
        }
    })
}

/// Make a witchy name a valid Rust identifier: the linker module-qualifies
/// functions as `stem.fn`, and `.` isn't legal in an identifier.
fn ident(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect()
}

fn rust_ty(t: &Type) -> Option<String> {
    match t {
        Type::Named(n, args) => match n.as_str() {
            "Int" | "Duration" => Some("i64".into()),
            "Float" => Some("f64".into()),
            "Bool" => Some("bool".into()),
            "String" => Some("String".into()),
            // A list maps to a Rust Vec of its element type.
            "List" => Some(format!("Vec<{}>", rust_ty(args.first()?)?)),
            // Option/Result map onto Rust's, with their element types.
            "Option" => Some(format!("Option<{}>", rust_ty(args.first()?)?)),
            "Result" => Some(format!(
                "Result<{}, {}>",
                rust_ty(args.first()?)?,
                rust_ty(args.get(1)?)?
            )),
            // A user record/enum type maps to its Rust struct/enum (if registered).
            other if RECORD_FIELDS.with(|r| r.borrow().contains_key(other)) => {
                Some(other.to_string())
            }
            other if ENUM_NAMES.with(|s| s.borrow().contains(other)) => Some(other.to_string()),
            _ => None,
        },
        // A tuple maps to a Rust tuple, supported when all elements are.
        Type::Tuple(ts) => {
            let parts: Option<Vec<String>> = ts.iter().map(rust_ty).collect();
            parts.map(|p| format!("({})", p.join(", ")))
        }
        _ => None,
    }
}

fn bin_op(op: BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::LtEq => "<=",
        BinOp::Gt => ">",
        BinOp::GtEq => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
        BinOp::BitAnd => "&",
        BinOp::BitOr => "|",
        BinOp::BitXor => "^",
        BinOp::Shl => "<<",
        BinOp::Shr => ">>",
        BinOp::Concat => "+",
    }
}

fn expr_kind(e: &Expr) -> &'static str {
    match e {
        Expr::List(_) => "list",
        Expr::Tuple(_) => "tuple",
        Expr::MethodCall { .. } => "method call",
        Expr::Apply { .. } => "function-value application",
        Expr::Ctor { .. } => "constructor",
        Expr::Field { .. } => "field access",
        Expr::Lambda { .. } => "closure",
        Expr::Record { .. } | Expr::RecordUpdate { .. } => "record",
        Expr::Try(_) => "`?`",
        Expr::As { .. } => "`as`",
        Expr::Match { .. } => "match",
        Expr::Range { .. } => "range value",
        Expr::Index { .. } => "index",
        Expr::WhileLet { .. } => "while-let",
        Expr::Spawn { .. } => "spawn",
        _ => "expression",
    }
}
